version: "3.7"

services:

  db:
    container_name: billtracker_db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    restart: unless-stopped

  pgadmin:
    container_name: billtracker_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - ./pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    restart: unless-stopped

volumes:
  db:
  pgadmin: