version: "3.7"

services:

  be:
    container_name: billtracker_be
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      BILLTRACKER_CONNECTIONSTRINGS__DATABASE: "Server=billtracker_db;Database=BillTracker;Port=5432;User Id=postgres;Password=123456;Timeout=120;"
    ports:
      - 5000:80
    restart: on-failure
    depends_on:
      - db
      
  db:
    container_name: billtracker_db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    restart: on-failure

  pgadmin:
    container_name: billtracker_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - ./pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    restart: on-failure

volumes:
  db:
  pgadmin: