name: BillTracker WebApi CD

env:
  IS_RELEASE: startsWith(GITHUB.REF, 'refs/tags/v')

on: 
  workflow_dispatch:

  push:
    tags: [ 'v*.*.*' ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set scripts permissions
      run: chmod +x ./build/*.sh

    - name: Build
      if: ${{ env.IS_RELEASE == false }}
      run: ./build/image-build-and-push.sh

    - name: Build & Publish Image
      if: ${{ env.IS_RELEASE == true }}
      run: ./build/image-build-and-push.sh --release-tag=${{ steps.vars.outputs.tag }}

    - name: Release
      if: ${{ env.IS_RELEASE == true }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart --name billtracker-api-dev --resource-group billtracker-api-dev --subscription a08721a6-b871-437b-9b3b-b64c0beec2b7
