name: BillTracker WebApi CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build & Publish Image
      run: "$GITHUB_WORKSPACE/build/image-build-and-push.sh"
    - name: Release
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart --name billtracker-api-dev --resource-group billtracker-api-dev --subscription a08721a6-b871-437b-9b3b-b64c0beec2b7
