name: BillTracker WebApi CD

on: 
  workflow_dispatch:

  pull_request:
    branches: [ main ]
    paths: 
    - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set scripts permissions
      run: chmod +x ./build/*.sh

    - name: Build
      if: GITHUB.REF != 'refs/heads/main'
      run: ./build/image-build-and-push.sh --no-publish

    - name: Build & Publish Image
      if: GITHUB.REF == 'refs/heads/main' && startsWith(GITHUB.REF, 'refs/tags/v')
      run: ./build/image-build-and-push.sh

    - name: Release
      if: GITHUB.REF == 'refs/heads/main' && startsWith(GITHUB.REF, 'refs/tags/v')
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart --name billtracker-api-dev --resource-group billtracker-api-dev --subscription a08721a6-b871-437b-9b3b-b64c0beec2b7
