name: BillTracker WebApi CD

on: 
  workflow_dispatch:

  push:
    branches: [ main ]
    paths: 
    - 'src/**'
  pull_request:
    branches: [ main ]
    paths: 
    - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set scripts permissions
      run: chmod +x ./build/*.sh

    - name: Build
      if: GITHUB.REF != 'refs/heads/main'
      run: ./build/image-build-and-push.sh --no-publish

    - name: Build & Publish Image
      if: GITHUB.REF == 'refs/heads/main'
      run: ./build/image-build-and-push.sh