name: BillTracker WebApi CD

env:
  IS_RELEASE: 

on: 
  workflow_dispatch:

  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Check output
      run: |
        echo ${{ steps.vars.outputs.tag }}

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set scripts permissions
      run: chmod +x ./build/*.sh

    # - name: Build
    #   if: ${{ !startsWith(steps.vars.outputs.tag, 'v') }}
    #   run: ./build/image-build-and-push.sh

    - name: Build & Publish Image
      run: ./build/image-build-and-push.sh --release-tag=${{ steps.vars.outputs.tag }}

    - name: Release
      if: ${{ startsWith(steps.vars.outputs.tag, 'v') }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart --name billtracker-api-dev --resource-group billtracker-api-dev --subscription a08721a6-b871-437b-9b3b-b64c0beec2b7
